name: Run R Script Daily

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch: {}
  
jobs:
  run-r-script:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install packages
        run: Rscript -e 'install.packages(c("tidyverse", "tidymodels", "here", "showtext", "httr", "magick", "grid", "gridExtra", "jsonlite", "zoo", "scales", "shiny", "rsconnect", "baseballr"))'
        
      - name: Run script
        run: Rscript processing/reg_season_predictions.R