name: Run R Script Daily

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch: {}

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies (CRAN + system)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tidyverse
            httr
            tidymodels
            jsonlite
            magick
            zoo
            here
            rvest
            gridExtra
            googledrive
            scales
            shiny
            rsconnect
            showtext
            xgboost
            
      - name: Install remotes
        run: Rscript -e 'install.packages("remotes", repos="https://cloud.r-project.org")'
        
      - name: Install baseballr
        run: Rscript -e 'remotes::install_github("BillPetti/baseballr", auth_token = Sys.getenv("GITHUB_TOKEN"))'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Run script
        run: Rscript processing/reg_season_predictions.R
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
